name: Tag Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.21"

      - name: Clean Go cache
        run: |
          go clean -cache -modcache -i -r

      - name: Build for multiple platforms
        run: |
          CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o ecsctl-darwin-amd64
          CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w" -o ecsctl-darwin-arm64
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o ecsctl-linux-amd64
          CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -ldflags="-s -w" -o ecsctl-linux-arm64
          CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o ecsctl-windows-amd64.exe

      - name: Extract Tag Name
        id: extract_tag
        run: echo "TAG_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: "${{ env.TAG_NAME }}"
          body: "Release for version ${{ env.TAG_NAME }}"
          draft: false
          prerelease: false

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ecsctl-darwin-amd64
          asset_name: ecsctl-darwin-amd64
          asset_content_type: application/octet-stream

      - name: Upload Release Assets - Darwin ARM64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ecsctl-darwin-arm64
          asset_name: ecsctl-darwin-arm64
          asset_content_type: application/octet-stream

      - name: Upload Release Assets - Linux AMD64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ecsctl-linux-amd64
          asset_name: ecsctl-linux-amd64
          asset_content_type: application/octet-stream

      - name: Upload Release Assets - Linux ARM64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ecsctl-linux-arm64
          asset_name: ecsctl-linux-arm64
          asset_content_type: application/octet-stream

      - name: Upload Release Assets - Windows AMD64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ecsctl-windows-amd64.exe
          asset_name: ecsctl-windows-amd64.exe
          asset_content_type: application/x-msdownload

      - name: Calculate and Display SHA-256 for Homebrew
        run: |
          echo "SHA-256 for Homebrew Formula:"
          echo "Darwin AMD64:"
          shasum -a 256 ecsctl-darwin-amd64 | awk '{ print $1 }'
          echo "Darwin ARM64:"
          shasum -a 256 ecsctl-darwin-arm64 | awk '{ print $1 }'
          echo "Linux AMD64:"
          shasum -a 256 ecsctl-linux-amd64 | awk '{ print $1 }'
          echo "Linux ARM64:"
          shasum -a 256 ecsctl-linux-arm64 | awk '{ print $1 }'
          echo "Windows AMD64:"
          shasum -a 256 ecsctl-windows-amd64.exe | awk '{ print $1 }'

      - name: Display Release URL
        run: |
          echo "Release URL: ${{ steps.create_release.outputs.html_url }}"
